server_load: 7
heartbeat_interval: 5
min_nodes: 2
min_queue_length: 1
bulletin_board:
  host: 'localhost'
  port: 8080
nodes:
  - id: 1
    host: 'localhost'
    port: 8081
  - id: 2
    host: 'localhost'
    port: 8082