clients:
    - host: localhost
      port: 50256
      promPort: 50257
    - host: localhost
      port: 50228
      promPort: 50229
    - host: localhost
      port: 50233
      promPort: 50234
    - host: localhost
      port: 50241
      promPort: 50242
    - host: localhost
      port: 50246
      promPort: 50247
    - host: localhost
      port: 50251
      promPort: 50252
relays:
    - host: localhost
      port: 50206
      promPort: 50207
    - host: localhost
      port: 50211
      promPort: 50212
    - host: localhost
      port: 50218
      promPort: 50219
    - host: localhost
      port: 50223
      promPort: 50224
    - host: localhost
      port: 50193
      promPort: 50194
    - host: localhost
      port: 50198
      promPort: 50199
