global:
    scrape_interval: 15s
    external_labels:
        monitor: pi_t
scrape_configs:
    - job_name: client-3
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9103
    - job_name: client-4
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9104
    - job_name: client-5
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9105
    - job_name: client-6
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9106
    - job_name: client-1
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9101
    - job_name: client-2
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9102
    - job_name: relay-4
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9204
    - job_name: relay-5
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9205
    - job_name: relay-6
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9206
    - job_name: relay-1
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9201
    - job_name: relay-2
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9202
    - job_name: relay-3
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:9203
