global:
    scrape_interval: 15s
    external_labels:
        monitor: pi_t
scrape_configs:
    - job_name: client-1
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53080
    - job_name: client-2
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53085
    - job_name: client-3
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53090
    - job_name: client-4
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53095
    - job_name: client-5
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53100
    - job_name: client-6
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53105
    - job_name: relay-4
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53127
    - job_name: relay-5
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53133
    - job_name: relay-6
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53138
    - job_name: relay-1
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53110
    - job_name: relay-2
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53116
    - job_name: relay-3
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:53122
rule_files:
    - /Users/hanma/Documents/GitHub/pi_t-experiment/internal/model/bulletin_board/metrics/rules.yml
