global:
    scrape_interval: 15s
    external_labels:
        monitor: pi_t
scrape_configs:
    - job_name: client-4
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:57000
    - job_name: client-5
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:57005
    - job_name: client-6
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:57010
    - job_name: client-1
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:56985
    - job_name: client-2
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:56990
    - job_name: client-3
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:56995
    - job_name: relay-1
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:57015
    - job_name: relay-2
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:57020
    - job_name: relay-3
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:57025
    - job_name: relay-4
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:57030
    - job_name: relay-5
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:57035
    - job_name: relay-6
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:57040
