global:
    scrape_interval: 15s
    external_labels:
        monitor: pi_t
scrape_configs:
    - job_name: client-2
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62174
    - job_name: client-3
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62183
    - job_name: client-4
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62188
    - job_name: client-5
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62194
    - job_name: client-6
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62199
    - job_name: client-1
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62161
    - job_name: relay-2
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62209
    - job_name: relay-3
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62214
    - job_name: relay-4
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62219
    - job_name: relay-5
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62224
    - job_name: relay-6
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62232
    - job_name: relay-1
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:62204
rule_files:
    - /Users/hanma/Documents/GitHub/pi_t-experiment/internal/model/bulletin_board/metrics/rules.yml
