global:
    scrape_interval: 15s
    external_labels:
        monitor: pi_t
scrape_configs:
    - job_name: client-1
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61073
    - job_name: client-2
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61079
    - job_name: client-3
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61084
    - job_name: client-4
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61092
    - job_name: client-5
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61097
    - job_name: client-6
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61102
    - job_name: relay-1
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61107
    - job_name: relay-2
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61112
    - job_name: relay-3
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61117
    - job_name: relay-4
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61125
    - job_name: relay-5
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61130
    - job_name: relay-6
      scrape_interval: 5s
      static_configs:
        - targets:
            - localhost:61135
rule_files:
    - /Users/hanma/Documents/GitHub/pi_t-experiment/internal/model/bulletin_board/metrics/rules.yml
